### PR TITLE
Support motion images

### PR DESCRIPTION
**Pull request by JaredTherriault**

### CODE REVIEW

**Comment by astalavistababe** [comment]
Failed to get frame from PIL: 'cv2.VideoCapture' object has no attribute 'seek'!

**Comment by JaredTherriault** [comment]
> Failed to get frame from PIL: 'cv2.VideoCapture' object has no attribute 'seek'!

Where, specifically? Do you get a stack trace?

**Comment by astalavistababe** [comment]
Do you get a stack trace?
No. 
How to get stack trace?

**Comment by JaredTherriault** [comment]
> Do you get a stack trace? No. How to get stack trace?

That's done in debugging. Ok, can you give me some steps to reproduce the issue? Does it occur with specific types of media or after doing a certain thing? Can you provide for me the media with which the issue occurs?

**Pull request merged**
