### PR TITLE
sort videos and faces lists alphanumerically

### PR DESCRIPTION
**Pull request by JaredTherriault**

### CODE REVIEW

**Comment by astalavistababe** [comment]
Fix mouse wheel seeking on timeline; add avg fps entry so users can find the best settings for realtime playback

Having this issue!
  File "E:\Rope-Next-StableV2\Rope-main\rope\GUIElements.py", line 579, in update_timeline_handle
    self.fps_history.append(1.0 / (time.time() - self.last_update_time))
ZeroDivisionError: float division by zero

**Comment by JaredTherriault** [comment]
How did you even find my hobby branch haha

Well thank you, easy to fix. I'll push it now.

**Comment by JaredTherriault** [comment]
Ok, did some cleanup. If you want to use all the latest changes, try the dev-merge branch from my fork.

**Comment by astalavistababe** [comment]
> Ok, did some cleanup. If you want to use all the latest changes, try the dev-merge branch from my fork.

O thanks, sorry for this late reply from my side.
Is it possible to add custom fps option so 60fps videos can be played in 30 or 24 fps?
Because i have RTX3060, after swap+restorer video plays at 30-35 max fps.
It would be great if custom fps added, so frames can be dropped and video can be played in realtime.

**Comment by JaredTherriault** [comment]
> > Ok, did some cleanup. If you want to use all the latest changes, try the dev-merge branch from my fork.
> 
> O thanks, sorry for this late reply from my side. Is it possible to add custom fps option so 60fps videos can be played in 30 or 24 fps? Because i have RTX3060, after swap+restorer video plays at 30-35 max fps. It would be great if custom fps added, so frames can be dropped and video can be played in realtime.

It's possible but not quite fast enough to allow any arbitrary frame rate, best I could do is some kind of frame skip so we can only show every x frame which would effectively reduce 60fps to 30.

The current application uses opencv to read frames sequentially. To reduce to an arbitrary rate we would need to interpolate from keyframes. Fastest way to do that is to use ffmpeg, but that's still not quite fast enough for real-time unless the arbitrary rate is under 12fps and that's with a fast cpu if face swap is also enabled. gpu decoding is actually slower and I have a 4090.

All this to say that extracting 24 fps from 60 in realtime with a face swap isn't really possible with current technology, but we can at the very least discard every x frames at a constant rate. I'll look into adding that. 

In the meantime you could always ask chatgpt to write you a python script to convert videos from 60fps to 24fps or something.

**Comment by astalavistababe** [comment]
Thanks for your feedback on my comment and i will let you know if there any issues with your new changes in code.
And you have 4090 still slower, then my expectations are very high with my 3060, so for now let technology evolve in future will see then, and again thanks and happy swapping :) 👍

**Comment by astalavistababe** [comment]
And this are some repos if they might new and if they can help,
https://github.com/NevermindNilas/ffmpegcv
https://github.com/NevermindNilas/ffmpy

And also i am on discord channel of alucard rope - next and hillobar rope if your there we can have discussion there, Astalavista.

**Comment by JaredTherriault** [comment]
No problem, thanks for the good idea. If you update dev-merge you'll find the new frame skipping parameters if you want to try them out. The feature needs a lot of work still but it should function on a basic level for now. You can find the new button group and slider at the bottom of the parameters panel. You can choose to keep frame skipping off, set a manual constant frame skip or let the application decide with auto. See if that helps!

**Pull request merged**
